### ISSUE TITLE
디렉토리 구조 변경 요청

### ISSUE THREAD

**Issue by pj4316** [Doobu-L/CommuProject#1]
- `.idea` gitignore에 추가
-  root로 src 이동
- maven -> gradle로 변경

**Comment by Doobu-L** [comment]
테스트 왕

**Comment by pj4316** [comment]
테스트 왕?

**Comment by Doobu-L** [comment]
maven -> gradle로 convert 는 추후 하겠습니다.

**Comment by pj4316** [comment]
[빌더 변경 요청 이슈](https://github.com/Doobu-L/CommuProject/issues/8) 에서 다루므로 해당 issue 종료합니다.
